In [1]:
'''
날짜 : 2020/08/10
이름 : 이태훈
내용 : Numpy (수치해석 패키지) 실습하기
'''

'\n날짜 : 2020/08/10\n이름 : 이태훈\n내용 : Numpy (수치해석 패키지) 실습하기\n'

In [3]:
import numpy as np

In [5]:
#벡터생성
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [7]:
v2 = np.arange(5)
v2

array([0, 1, 2, 3, 4])

In [9]:
# 0 ~ 1 사이의 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.97467185, 0.37247067, 0.85577605, 0.57947816, 0.86755273,
       0.58392289, 0.91921055, 0.55925974, 0.14951494, 0.41970157,
       0.51086811, 0.57608338, 0.12840474, 0.93593171, 0.25007157,
       0.96224907, 0.56622115, 0.20594927, 0.54560473, 0.59736337,
       0.65400991, 0.43957038, 0.69356182, 0.76210673, 0.29689633,
       0.84789351, 0.81305124, 0.23850233, 0.11281699, 0.84069856,
       0.1311998 , 0.76248166, 0.6141286 , 0.83052984, 0.24366811,
       0.53003817, 0.24185147, 0.87563516, 0.60106182, 0.06039534,
       0.09411384, 0.39159398, 0.88491855, 0.03019329, 0.04980264,
       0.24282681, 0.01438281, 0.70642668, 0.00761441, 0.67562312,
       0.89583501, 0.30975533, 0.85699301, 0.30540816, 0.19006518,
       0.19036328, 0.46245877, 0.61606833, 0.47855934, 0.66080757,
       0.48018199, 0.19379967, 0.9205508 , 0.10456249, 0.92247443,
       0.75338127, 0.68524786, 0.81913855, 0.68255966, 0.35837395,
       0.90242913, 0.09821809, 0.26967205, 0.28119455, 0.74466

In [11]:
# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-2.90440674e+00,  2.77206349e-01,  9.69886877e-01, -5.19069927e-01,
       -1.19230748e+00,  4.54001582e-01, -8.77334557e-01,  7.32005515e-01,
        2.22588398e-01, -7.50035084e-01,  5.14437528e-01,  1.60463588e+00,
       -1.40432376e+00,  7.55170433e-02,  1.02767339e+00, -1.28587527e+00,
        1.74531291e+00, -3.40832006e-01, -3.07263626e-01,  1.44175037e-02,
       -8.07266911e-02,  8.58966040e-01, -9.77310660e-01, -1.84710369e+00,
       -6.54564410e-01, -1.65298474e-01, -9.96359134e-01,  1.47746579e+00,
       -2.87938346e-01, -7.82938870e-01, -3.05540926e-01, -4.24693746e-01,
        5.88415512e-01, -9.36049763e-01,  1.19049746e+00, -7.54661311e-01,
        2.50230362e+00,  3.13838200e-01, -9.06982589e-01, -2.80977750e-01,
       -1.76115602e+00, -2.65161554e-01,  4.49135204e-01, -1.29078311e+00,
        5.99772484e-01, -5.02617864e-01,  3.28034475e-01,  1.91341640e-01,
        1.05459354e+00, -5.00401041e-01,  8.37409217e-01, -8.43000412e-01,
        8.49185003e-01,  

In [12]:
# 평균 0 , 표준편차가 1인 정규분포를 따르는 임의의 실수 100개
rand3 = np.random.normal(0, 1, 100)
rand3

array([-2.35428077e-01,  4.95152870e-01, -1.94126958e-01, -4.59559875e-01,
        6.91659562e-01, -9.14119498e-02, -2.22996919e-01,  9.14796799e-01,
        2.11923921e+00, -1.14792044e+00, -1.08604832e+00,  9.32503433e-01,
        5.60602310e-02,  1.32759770e+00,  5.43235522e-01, -7.14274546e-01,
       -9.00842928e-01,  1.19157603e+00, -9.40877176e-01,  5.13260064e-01,
       -4.69061165e-01, -4.25918553e-01,  1.11218852e+00, -1.21112278e+00,
       -3.47383154e-02,  4.68273497e-01, -2.62947072e-01, -5.55152936e-01,
        6.11238108e-01, -2.26735991e+00, -8.89457851e-01, -3.64704389e-01,
        2.08886987e+00,  8.92953263e-01,  9.96608869e-01, -1.06554912e+00,
       -1.38488448e+00, -3.14789520e-01,  1.11213720e+00, -7.76902711e-01,
       -3.24030477e-01,  1.84265426e-01,  8.91613385e-01, -3.54545419e-01,
       -3.94280146e-01, -8.79323979e-01,  2.07618807e+00, -1.43215514e+00,
        1.26386208e+00,  6.17919883e-02,  5.08181740e-01,  1.04029621e+00,
        4.13859108e-01,  